### ISSUE TITLE
Consider not deprecating Store::migrate

### ISSUE THREAD

**Issue by kontext-e** [buschmais/jqa-core-framework#21]
In https://github.com/kontext-e/jqassistant-plugins/issues/59 Dirk suggested to use Store::migrate to migrate nodes instead of creating new ones. Issue was solved, but now the 'migrate' method is deprecated and should be removed in jqa 1.6. Apparently there is no replacement since there is no other method with similiar signature and no comment what should be used instead. Removing API Methods without replacements breaks Plugins.

**Comment by DirkMahler** [comment]
The new way to go is Store#addDescriptorType.
