### ISSUE TITLE
jUnit report plugin

### ISSUE THREAD

**Issue by simonnagl** [buschmais/jqa-core-framework#28]
## Goal

A report plugin which outputs xml like jUnit. I would help implementing this. Is there a process getting a repository at https://github.com/jqassistant-contrib?

I could also just start implementing the plugin and notify you here when it is ready to be tested. Am I allowed to use the package `org.jqassistant.contrib.junitreport` as root package for the plugin?

## This would enable ...

jUnit reports are supported by many applications. For example GitLab supports JUnit test reports: https://docs.gitlab.com/ee/ci/junit_test_reports.html

## Resources

- jUnit report schema: https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd

**Comment by obfischer** [comment]
Hi @simonnagl, 

this is already supported. There should be a directory calles `target/jqassistant/report/junit/` after running jQAssistant. Can you please have a look at it and tell me if this is what you need?

**Comment by simonnagl** [comment]
Wow, thank you for the quick answer! I totally missed this directory. This totally fits my needs. If there is something missing, I will open a new issue or PR.

**Comment by obfischer** [comment]
Yes, please do so. We need much more input from our users.

**Comment by DirkMahler** [comment]
For a Jenkins setup there's a tutorial: https://101.jqassistant.org/reporting-jqassistant-results-in-jenkins/index.html

**Comment by simonnagl** [comment]
Just to let you know. Test Reports in Gitlab works.

**Comment by DirkMahler** [comment]
Cool - thanks for the feedback!
